#!/bin/bash
MD5SUM='cat /root/crontabsum'
NEW='md5sum /etc/crontab | cut -d " " -f 1'

if [ "$MD5SUM" != "$NEW" ] ; then
	echo "/etc/crontab a ete modifie ces dernieres 24h" | mail -s " /etc/crontab " root
	# envoie un email local à root (echo -e "corps" | mail -s 'sujet' root)
	exit 1
fi

# pour creer la tache planifie on fait avec crontab -e (commande pour editer la liste des taches) :
# 0 0 * * * /path/to/file
